{% set version = "v0.0.5" %}

package:
    name: sequenoscope
    version: {{ version }}

source:
    url: https://github.com/phac-nml/sequenoscope/archive/{{ version }}.tar.gz
    sha256: fc9f4cab412c823b678aa0e93a65a5fe54f2f3c4420c119320cc949f987d184d   

build:
    number: 1
    noarch: python
    script: python -m pip install .

requirements:
    build:
        - python >=3.7.12,<4
        - pip >=23.2.1
    run:
        - python >=3.7.12,<4
        - pytest >=7.4.2
        - pandas >=1.3.5
        - samtools >=1.6
        - pysam >=0.16.0
        - minimap2 >=2.26
        - mash >=2.3
        - fastp >=0.22.0
        - seqtk >=1.4
        - plotly >=5.16.1
        - biopython >=1.79
        - scipy >=1.7.3
        - six >=1.16.0
        - numpy >=1.21.6
test:
    import:
        - sequenoscope
    commands:
        - "sequenoscope --help"


about:
    license: Apache 2
    summary: The following marks the first release for a versatile bioinformatic pipeline for the analysis of sequencing data. The pipeline handles different types of sequencing data and has specific tools that give insight into adaptive sampling sequencing introduced by Oxford Nanopore sequencers.
    author: Abdallah Meknas, James Robertson
    home: https://github.com/phac-nml/sequenoscope